### ISSUE TITLE
Division by 0 in check_memory_by_ssh.py", line 159 [with solution]

### ISSUE THREAD

**Issue by jrierab** [naparuba/check-linux-by-ssh#23]
If a server does not have swap memory, the mentioned script fails with:

Traceback (most recent call last):
File "/var/lib/shinken/libexec/check_memory_by_ssh.py", line 159, in
perfdata += ' %s=%s%%;;;0%%;100%%' % (k, int(100 * float(v)/swap_total))
ZeroDivisionError: float division by zero

This can be taken care by adding a simple check:
if(swap_total==0):
perfdata += ' %s=%s%%;;;0%%;100%%' % (k, 0)
else:
perfdata += ' %s=%s%%;;;0%%;100%%' % (k, int(100 * float(v)/swap_total))

NB: This was previously reported https://github.com/naparuba/shinken/issues/1396 but t0xicCode suggected to move it here.

**Comment by LoveIsGrief** [comment]
I would like to confirm this. It'd be nice if the fix could added to the code. This can spam a shinken very easily.

**Comment by david-guenault** [comment]
fixed in #40. I close this one
