### ISSUE TITLE
Custom views in Shinken WebUI

### ISSUE THREAD

**Issue by mohierf** [naparuba/check-linux-by-ssh#7]
When installing module to check Linux host by SSH (thanks to your tutorial http://shinkenlab.io/online-course-1-installation/ ...), I get three new custom views in Shinken Web UI ... but where are those views ? I am interested in ...

**Comment by Dual-Boot** [comment]
Hello,

A little news: the linux tab is working now. I found a workaround into this file : 
/etc/shinken/packs/linux-ssh/templates.cfg
I have changed the following line : 
custom_views                        +linux_ssh,linux_ssh_memory,linux_ssh_processes
by custom_views                 +linux,linux_ssh_memory,linux_ssh_processes
Then restart shinken.
 I can not find out for the other tabs.

Regards,

**Comment by aljawo** [comment]
Hello gentlemen,
  any news about this problem? All the ssh check for localhost are still showing as "WARNING" and the custom views are not reachable (error 404)

Thanks.

**Comment by mohierf** [comment]
The custom views do not exist for linux_ssh ... the people that di implement the checks never provided those views :/

**Comment by aljawo** [comment]
Thanks my friend. What about the WARNING status of all the local checks ?

![image](https://cloud.githubusercontent.com/assets/15675433/13222287/49083f0c-d94d-11e5-9aa3-8570989fff50.png)

Thanks again !

**Comment by mohierf** [comment]
You should try to launch the checks command on the command line because the "Traceback (most ..." message is the beginning of a Python exception message !

**Comment by aljawo** [comment]
Thanks again for the prompt answer.. I tried that and I get the proper values, that is why it is very strange.

![image](https://cloud.githubusercontent.com/assets/15675433/13223562/b7337f6e-d952-11e5-9ac5-aa4a3c6b3072.png)

**Comment by mohierf** [comment]
Have a look in the shinken configuration file that contains the definition of the commands to check wether it is the same ... not sure at all ! This file is somewhere near `/etc/shinken/packs/linux-ssh`...

**Comment by aljawo** [comment]
Thanks ! That is a very interesting lead to follow... the commands are within the commands.cfg file exactly where you pointed me to.

![image](https://cloud.githubusercontent.com/assets/15675433/13225432/cb42fc48-d95a-11e5-9934-1696b30774d8.png)

I am not quite sure where those parameter variables are fetching the info from.. I checked the the /etc/shinken/resourses.d/ssh.cfg file and the names of the variables don't match at all, but again, not sure that this is the proper place to look for...

**Comment by mohierf** [comment]
You also have other cfg files in the same directory and you should indicate your SSH connexion parameters in one of these files (`templates.cfg` I guess...).

And please have a look at how Shinken uses the $ variables in the doc ...

**Comment by aljawo** [comment]
Thanks, Now I need to figure out how debug those variables and see the
content in real time.

**Comment by david-guenault** [comment]
@mohierf  Can i close this one since it is related to the first webui version ?

**Comment by mohierf** [comment]
Closed
